const express = require('express');
const auth = require('../middleware/auth');
const Resume = require('../models/Resume');
const CareerRoadmap = require('../models/CareerRoadmap');
const aiService = require('../services/aiService');
const geminiService = require('../services/geminiService');

const router = express.Router();

// Get sample job postings
router.get('/jobs', async (req, res) => {
  try {
    const jobs = aiService.getSampleJobPostings();
    res.json(jobs);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Upload resume from file text (text extracted in browser, sent as JSON)
router.post('/upload-resume-text', auth, async (req, res) => {
  try {
    const { resumeText, fileName } = req.body;

    if (!resumeText || resumeText.trim().length < 10) {
      return res.status(400).json({ message: 'Resume text is too short or empty' });
    }

    // Parse resume using AI
    const parsed = await geminiService.parseResumeFromText(resumeText);

    // Ensure skills array is populated
    if (!parsed.skills || parsed.skills.length === 0) {
      parsed.skills = ['See resume text'];
    }

    // Save or update resume
    let resume = await Resume.findOne({ userId: req.userId });
    if (resume) {
      resume.fullName = parsed.fullName || resume.fullName;
      resume.email = parsed.email || resume.email;
      resume.phone = parsed.phone || resume.phone;
      resume.skills = parsed.skills;
      resume.experience = parsed.experience || resume.experience;
      resume.education = parsed.education || resume.education;
      resume.certifications = parsed.certifications || resume.certifications;
      resume.resumeText = resumeText;
      resume.fileName = fileName || 'uploaded_resume';
      resume.updatedAt = new Date();
    } else {
      resume = new Resume({
        userId: req.userId,
        fullName: parsed.fullName || '',
        email: parsed.email || '',
        phone: parsed.phone || '',
        skills: parsed.skills,
        experience: parsed.experience || [],
        education: parsed.education || [],
        certifications: parsed.certifications || [],
        resumeText,
        fileName: fileName || 'uploaded_resume',
      });
    }

    await resume.save();

    res.status(201).json({
      success: true,
      resume: {
        _id: resume._id,
        fullName: resume.fullName,
        email: resume.email,
        skills: resume.skills,
        experience: resume.experience,
        education: resume.education,
        certifications: resume.certifications,
        fileName: resume.fileName,
        updatedAt: resume.updatedAt
      },
      parsedData: parsed
    });
  } catch (error) {
    console.error('Resume upload error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Analyze resume against a job AND generate roadmap if skills < required
router.post('/analyze-and-roadmap', auth, async (req, res) => {
  try {
    const { jobPostingId, jobData } = req.body;

    const resume = await Resume.findOne({ userId: req.userId });
    if (!resume) {
      return res.status(404).json({ message: 'Resume not found. Please upload your resume first.' });
    }

    const jobPosting = jobData || aiService.getSampleJobPostings().find(j => j._id === jobPostingId);
    if (!jobPosting) {
      return res.status(404).json({ message: 'Job posting not found' });
    }

    // Skill match analysis
    const analysis = aiService.analyzeResume(resume, jobPosting);

    let roadmap = null;
    let savedRoadmap = null;

    // Auto-generate roadmap if there are missing skills
    if (analysis.missingSkills && analysis.missingSkills.length > 0) {
      try {
        const currentLevel = aiService.determineCurrentLevel(resume);
        const aiRoadmap = await geminiService.generateLearningRoadmap(
          analysis,
          jobPosting.title,
          currentLevel
        );

        const roadmapData = aiService.generateRoadmap(resume, jobPosting, analysis);

        savedRoadmap = await CareerRoadmap.create({
          userId: req.userId,
          jobPostingId: jobPostingId || jobPosting._id,
          ...roadmapData,
          roadmapSteps: aiRoadmap.phases || roadmapData.roadmapSteps
        });

        roadmap = savedRoadmap;
      } catch (roadmapError) {
        console.error('Roadmap generation error:', roadmapError.message);
        // Return analysis even if roadmap generation fails
      }
    }

    res.json({
      success: true,
      analysis,
      roadmap,
      jobPosting: {
        _id: jobPosting._id,
        title: jobPosting.title,
        company: jobPosting.company,
        requiredSkills: jobPosting.requiredSkills
      },
      autoGeneratedRoadmap: !!roadmap
    });
  } catch (error) {
    console.error('Analyze and roadmap error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Analyze resume against job (legacy endpoint kept for compatibility)
router.post('/analyze', auth, async (req, res) => {
  try {
    const { jobPostingId, jobData } = req.body;

    const resume = await Resume.findOne({ userId: req.userId });
    if (!resume) {
      return res.status(404).json({ message: 'Resume not found. Please upload your resume first.' });
    }

    const jobPosting = jobData || aiService.getSampleJobPostings().find(j => j._id === jobPostingId);
    if (!jobPosting) {
      return res.status(404).json({ message: 'Job posting not found' });
    }

    const analysis = aiService.analyzeResume(resume, jobPosting);
    res.json(analysis);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Generate career roadmap with AI
router.post('/roadmap', auth, async (req, res) => {
  try {
    const { jobPostingId, jobData } = req.body;

    const resume = await Resume.findOne({ userId: req.userId });
    if (!resume) {
      return res.status(404).json({ message: 'Resume not found. Please upload your resume first.' });
    }

    const jobPosting = jobData || aiService.getSampleJobPostings().find(j => j._id === jobPostingId);
    if (!jobPosting) {
      return res.status(404).json({ message: 'Job posting not found' });
    }

    const analysis = aiService.analyzeResume(resume, jobPosting);

    const aiRoadmap = await geminiService.generateLearningRoadmap(
      analysis,
      jobPosting.title,
      aiService.determineCurrentLevel(resume)
    );

    const roadmap = aiService.generateRoadmap(resume, jobPosting, analysis);

    const savedRoadmap = await CareerRoadmap.create({
      userId: req.userId,
      jobPostingId: jobPostingId || jobPosting._id,
      ...roadmap,
      roadmapSteps: aiRoadmap.phases || roadmap.roadmapSteps
    });

    res.status(201).json(savedRoadmap);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Get user roadmaps
router.get('/roadmaps', auth, async (req, res) => {
  try {
    const roadmaps = await CareerRoadmap.find({ userId: req.userId });
    res.json(roadmaps);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Upload/Update resume (legacy JSON endpoint)
router.post('/resume', auth, async (req, res) => {
  try {
    const { skills, experience, education, projects, certifications } = req.body;

    let resume = await Resume.findOne({ userId: req.userId });
    if (resume) {
      resume.skills = skills;
      resume.experience = experience;
      resume.education = education;
      resume.projects = projects;
      resume.certifications = certifications;
      resume.updatedAt = new Date();
    } else {
      resume = new Resume({
        userId: req.userId,
        skills,
        experience,
        education,
        projects,
        certifications
      });
    }

    await resume.save();
    res.status(201).json(resume);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Get user resume
router.get('/resume', auth, async (req, res) => {
  try {
    const resume = await Resume.findOne({ userId: req.userId });
    if (!resume) {
      return res.status(404).json({ message: 'Resume not found' });
    }
    res.json(resume);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// AI-powered resume verification
router.post('/verify-resume', auth, async (req, res) => {
  try {
    const { jobRole, requiredSkills } = req.body;

    const resume = await Resume.findOne({ userId: req.userId });
    if (!resume) {
      return res.status(404).json({ message: 'Resume not found. Please upload your resume first.' });
    }

    const verification = await geminiService.verifyResumeEligibility(
      resume,
      jobRole,
      requiredSkills
    );

    res.json({
      success: true,
      verification
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Update learning progress
router.post('/roadmap-progress', auth, async (req, res) => {
  try {
    const { roadmapId, completedStep, skillLearned } = req.body;
    const LearningProgress = require('../models/LearningProgress');

    let progress = await LearningProgress.findOne({ userId: req.userId, roadmapId });

    if (!progress) {
      progress = new LearningProgress({
        userId: req.userId,
        roadmapId
      });
    }

    if (completedStep) {
      progress.completedSteps.push(completedStep);
    }

    if (skillLearned) {
      progress.skillsLearned.push(skillLearned);
    }

    const roadmap = await CareerRoadmap.findById(roadmapId);
    if (roadmap) {
      const totalSteps = roadmap.roadmapSteps.length;
      const completed = progress.completedSteps.length;
      progress.completionPercentage = Math.round((completed / totalSteps) * 100);
    }

    progress.lastUpdated = new Date();
    await progress.save();

    res.json({
      success: true,
      progress
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get learning progress
router.get('/roadmap-progress/:roadmapId', auth, async (req, res) => {
  try {
    const LearningProgress = require('../models/LearningProgress');
    const progress = await LearningProgress.findOne({
      userId: req.userId,
      roadmapId: req.params.roadmapId
    });

    if (!progress) {
      return res.status(404).json({ message: 'No progress found for this roadmap' });
    }

    res.json({
      success: true,
      progress
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
